INSERT INTO item VALUES (798,'Vision','Scroll','Arcane','No',NULL,NULL,'2,775 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (799,'Waves of Exhaustion','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (800,'Antipathy','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (801,'Clenched Fist','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (802,'Binding','Scroll','Arcane','No',NULL,NULL,'8,500 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (803,'Charm Monster, Mass','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (804,'Clone','Scroll','Arcane','No',NULL,NULL,'4,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (805,'Create Greater Undead','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (806,'Demand','Scroll','Arcane','No',NULL,NULL,'3,600 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (807,'Dimensional Lock','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (808,'Discern Location','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (809,'Horrid Wilting','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (810,'Incendiary Cloud','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (811,'Iron Body','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (812,'Maze','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (813,'Mind Blank','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (814,'Moment of Prescience','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (815,'Telekinetic Sphere','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (816,'Irresistible Dance','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (817,'Planar Binding, Greater','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (818,'Polar Ray','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (819,'Polymorph Any Object','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (820,'Power Word Stun','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (821,'Prismatic Wall','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (822,'Protection from Spells','Scroll','Arcane','No',NULL,NULL,'3,500 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (823,'Prying Eyes, Greater','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (824,'Scintillating Pattern','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (825,'Screen','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (826,'Shadow Evocation, Greater','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (827,'Shout, Greater','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (828,'Summon Monster VIII','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (829,'Sunburst','Scroll','Arcane','No',NULL,NULL,'3,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (830,'Symbol of Death','Scroll','Arcane','No',NULL,NULL,'8,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (831,'Symbol of Insanity','Scroll','Arcane','No',NULL,NULL,'8,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (832,'Sympathy','Scroll','Arcane','No',NULL,NULL,'4,500 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (833,'Temporal Stasis','Scroll','Arcane','No',NULL,NULL,'3,500 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (834,'Trap the Soul','Scroll','Arcane','No',NULL,NULL,'13,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (835,'Astral Projection','Scroll','Arcane','No',NULL,NULL,'4,870 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (836,'Crushing Hand','Scroll','Arcane','No',NULL,NULL,'3,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (837,'Dominate Monster','Scroll','Arcane','No',NULL,NULL,'3,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (838,'Energy Drain','Scroll','Arcane','No',NULL,NULL,'3,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (839,'Etherealness','Scroll','Arcane','No',NULL,NULL,'3,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (840,'Foresight','Scroll','Arcane','No',NULL,NULL,'3,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (841,'Freedom','Scroll','Arcane','No',NULL,NULL,'3,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (842,'Gate','Scroll','Arcane','No',NULL,NULL,'8,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (843,'Hold Monster, Mass','Scroll','Arcane','No',NULL,NULL,'3,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (844,'Imprisonment','Scroll','Arcane','No',NULL,NULL,'3,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (845,'Meteor Swarm','Scroll','Arcane','No',NULL,NULL,'3,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (846,'Mage\'s Disjunction','Scroll','Arcane','No',NULL,NULL,'3,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (847,'Power Word Kill','Scroll','Arcane','No',NULL,NULL,'3,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (848,'Prismatic Sphere','Scroll','Arcane','No',NULL,NULL,'3,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (849,'Refuge','Scroll','Arcane','No',NULL,NULL,'3,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (850,'Shades','Scroll','Arcane','No',NULL,NULL,'3,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (851,'Shapechange','Scroll','Arcane','No',NULL,NULL,'3,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (852,'Soul Bind','Scroll','Arcane','No',NULL,NULL,'3,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (853,'Summon Monster IX','Scroll','Arcane','No',NULL,NULL,'3,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (854,'Teleportation Circle','Scroll','Arcane','No',NULL,NULL,'4,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (855,'Time Stop','Scroll','Arcane','No',NULL,NULL,'3,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (856,'Wail of the Banshee','Scroll','Arcane','No',NULL,NULL,'3,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (857,'Weird','Scroll','Arcane','No',NULL,NULL,'3,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (858,'Wish','Scroll','Arcane','No',NULL,NULL,'28,825 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (859,'Create Water','Scroll','Divine','No',NULL,NULL,'12 gp 5 sp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (860,'Cure Minor Wounds','Scroll','Divine','No',NULL,NULL,'12 gp 5 sp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (861,'Detect Magic','Scroll','Divine','No',NULL,NULL,'12 gp 5 sp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (862,'Detect Poison','Scroll','Divine','No',NULL,NULL,'12 gp 5 sp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (863,'Flare','Scroll','Divine','No',NULL,NULL,'12 gp 5 sp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (864,'Guidance','Scroll','Divine','No',NULL,NULL,'12 gp 5 sp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (865,'Inflict Minor Wounds','Scroll','Divine','No',NULL,NULL,'12 gp 5 sp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (866,'Know Direction','Scroll','Divine','No',NULL,NULL,'12 gp 5 sp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (867,'Light','Scroll','Divine','No',NULL,NULL,'12 gp 5 sp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (868,'Mending','Scroll','Divine','No',NULL,NULL,'12 gp 5 sp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (869,'Purify Food and Drink','Scroll','Divine','No',NULL,NULL,'12 gp 5 sp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (870,'Read Magic','Scroll','Divine','No',NULL,NULL,'12 gp 5 sp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (871,'Resistance','Scroll','Divine','No',NULL,NULL,'12 gp 5 sp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (872,'Virtue','Scroll','Divine','No',NULL,NULL,'12 gp 5 sp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (873,'Alarm','Scroll','Divine','No',NULL,NULL,'100 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (874,'Bane','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (875,'Bless','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (876,'Bless Water','Scroll','Divine','No',NULL,NULL,'50 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (877,'Bless Weapon','Scroll','Divine','No',NULL,NULL,'100 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (878,'Calm Animals','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (879,'Cause Fear','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (880,'Charm Animal','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (881,'Command','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (882,'Comprehend Languages','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (883,'Cure Light Wounds','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (884,'Curse Water','Scroll','Divine','No',NULL,NULL,'50 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (885,'Deathwatch','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (886,'Detect Animals or Plants','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (887,'Detect Chaos/Evil/Good/Law','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (888,'Detect Snares and Pits','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (889,'Detect Undead','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (890,'Divine Favor','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (891,'Doom','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (892,'Endure Elements','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (893,'Entangle','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (894,'Entropic Shield','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (895,'Faerie Fire','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (896,'Goodberry','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (897,'Hide from Animals','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
