INSERT INTO item VALUES (698,'Permanency','Scroll','Arcane','No',NULL,NULL,'10,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (699,'Persistent Image','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (700,'Planar Binding, Lesser','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (701,'Prying Eyes','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (702,'Telepathic Bond','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (703,'Seeming','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (704,'Sending','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (705,'Shadow Evocation','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (706,'Song of Discord','Scroll','Arcane','No',NULL,NULL,'1,625 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (707,'Summon Monster V','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (708,'Symbol of Pain','Scroll','Arcane','No',NULL,NULL,'2,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (709,'Symbol of Sleep','Scroll','Arcane','No',NULL,NULL,'2,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (710,'Telekinesis','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (711,'Teleport','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (712,'Transmute Mud to Rock','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (713,'Transmute Rock to Mud','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (714,'Wall of Force','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (715,'Wall of Stone','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (716,'Waves of Fatigue','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (717,'Acid Fog','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (718,'Analyze Dweomer','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (719,'Animate Objects','Scroll','Arcane','No',NULL,NULL,'2,400 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (720,'Antimagic Field','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (721,'Bear\'s Endurance, Mass','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (722,'Forceful Hand','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (723,'Bull\'s Strength, Mass','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (724,'Cat\'s Grace, Mass','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (725,'Chain Lightning','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (726,'Circle of Death','Scroll','Arcane','No',NULL,NULL,'2,150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (727,'Contingency','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (728,'Control Water','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (729,'Create Undead','Scroll','Arcane','No',NULL,NULL,'2,350 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (730,'Cure Moderate Wounds, Mass','Scroll','Arcane','No',NULL,NULL,'2,400 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (731,'Disintegrate','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (732,'Dispel Magic, Greater','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (733,'Eagle\'s Splendor, Mass','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (734,'Eyebite','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (735,'Find the Path','Scroll','Arcane','No',NULL,NULL,'2,400 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (736,'Flesh to Stone','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (737,'Fox\'s Cunning, Mass','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (738,'Geas/Quest','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (739,'Globe of Invulnerability','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (740,'Guards and Wards','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (741,'Heroes\' Feast','Scroll','Arcane','No',NULL,NULL,'2,400 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (742,'Heroism, Greater','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (743,'Legend Lore','Scroll','Arcane','No',NULL,NULL,'1,900 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (744,'Mislead','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (745,'Mage\'s Lucubration','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (746,'Move Earth','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (747,'Freezing Sphere','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (748,'Owl\'s Wisdom, Mass','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (749,'Permanent Image','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (750,'Planar Binding','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (751,'Programmed Image','Scroll','Arcane','No',NULL,NULL,'1,675 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (752,'Repulsion','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (753,'Shadow Walk','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (754,'Stone to Flesh','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (755,'Suggestion, Mass','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (756,'Summon Monster VI','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (757,'Symbol of Fear','Scroll','Arcane','No',NULL,NULL,'2,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (758,'Symbol of Persuasion','Scroll','Arcane','No',NULL,NULL,'6,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (759,'Sympathetic Vibration','Scroll','Arcane','No',NULL,NULL,'2,400 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (760,'Transformation','Scroll','Arcane','No',NULL,NULL,'1,950 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (761,'True Seeing','Scroll','Arcane','No',NULL,NULL,'1,900 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (762,'Undeath to Death','Scroll','Arcane','No',NULL,NULL,'2,150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (763,'Veil','Scroll','Arcane','No',NULL,NULL,'1,650 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (764,'Wall of Iron','Scroll','Arcane','No',NULL,NULL,'1,700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (765,'Arcane Sight, Greater','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (766,'Banishment','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (767,'Grasping Hand','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (768,'Control Undead','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (769,'Control Weather','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (770,'Delayed Blast Fireball','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (771,'Instant Summons','Scroll','Arcane','No',NULL,NULL,'3,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (772,'Ethereal Jaunt','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (773,'Finger of Death','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (774,'Forcecage','Scroll','Arcane','No',NULL,NULL,'23775 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (775,'Hold Person, Mass','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (776,'Insanity','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (777,'Invisibility, Mass','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (778,'Limited Wish','Scroll','Arcane','No',NULL,NULL,'3,775 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (779,'Mage\'s Magnificent Mansion','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (780,'Mage\'s Sword','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (781,'Phase Door','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (782,'Plane Shift','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (783,'Power Word Blind','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (784,'Prismatic Spray','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (785,'Project Image','Scroll','Arcane','No',NULL,NULL,'2,280 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (786,'Reverse Gravity','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (787,'Scrying, Greater','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (788,'Sequester','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (789,'Shadow Conjuration, Greater','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (790,'Simulacrum','Scroll','Arcane','No',NULL,NULL,'7,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (791,'Spell Turning','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (792,'Statue','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (793,'Summon Monster VII','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (794,'Symbol of Stunning','Scroll','Arcane','No',NULL,NULL,'7,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (795,'Symbol of Weakness','Scroll','Arcane','No',NULL,NULL,'7,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (796,'Teleport Object','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (797,'Teleport, Greater','Scroll','Arcane','No',NULL,NULL,'2,275 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
