INSERT INTO item VALUES (898,'Hide from Undead','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (899,'Inflict Light Wounds','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (900,'Jump','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (901,'Longstrider','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (902,'Magic Fang','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (903,'Magic Stone','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (904,'Magic Weapon','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (905,'Obscuring Mist','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (906,'Pass without Trace','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (907,'Produce Flame','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (908,'Protection from Chaos/Evil/Good/Law','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (909,'Remove Fear','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (910,'Sanctuary','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (911,'Shield of Faith','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (912,'Shillelagh','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (913,'Speak with Animals','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (914,'Summon Monster I','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (915,'Summon Nature\'s Ally I','Scroll','Divine','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (916,'Animal Messenger','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (917,'Animal Trance','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (918,'Augury','Scroll','Divine','No',NULL,NULL,'175 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (919,'Barkskin','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (920,'Bear\'s Endurance','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (921,'Bull\'s Strength','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (922,'Calm Emotions','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (923,'Cat\'s Grace','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (924,'Chill Metal','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (925,'Consecrate','Scroll','Divine','No',NULL,NULL,'200 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (926,'Cure Moderate Wounds','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (927,'Darkness','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (928,'Death Knell','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (929,'Delay Poison','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (930,'Desecrate','Scroll','Divine','No',NULL,NULL,'200 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (931,'Eagle\'s Splendor','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (932,'Enthrall','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (933,'Find Traps','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (934,'Fire Trap','Scroll','Divine','No',NULL,NULL,'175 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (935,'Flame Blade','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (936,'Flaming Sphere','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (937,'Fog Cloud','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (938,'Gentle Repose','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (939,'Gust of Wind','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (940,'Heat Metal','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (941,'Hold Animal','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (942,'Hold Person','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (943,'Inflict Moderate Wounds','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (944,'Make Whole','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (945,'Owl\'s Wisdom','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (946,'Reduce Animal','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (947,'Remove Paralysis','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (948,'Resist Energy','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (949,'Restoration, Lesser','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (950,'Shatter','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (951,'Shield Other','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (952,'Silence','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (953,'Snare','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (954,'Soften Earth and Stone','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (955,'Sound Burst','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (956,'Speak with Plants','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (957,'Spider Climb','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (958,'Spiritual Weapon','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (959,'Status','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (960,'Summon Monster II','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (961,'Summon Nature\'s Ally II','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (962,'Summon Swarm','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (963,'Tree Shape','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (964,'Undetectable Alignment','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (965,'Warp Wood','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (966,'Wood Shape','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (967,'Zone of Truth','Scroll','Divine','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (968,'Animate Dead','Scroll','Divine','No',NULL,NULL,'625 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (969,'Bestow Curse','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (970,'Blindness/Deafness','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (971,'Call Lightning','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (972,'Contagion','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (973,'Continual Flame','Scroll','Divine','No',NULL,NULL,'425 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (974,'Create Food and Water','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (975,'Cure Serious Wounds','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (976,'Darkvision','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (977,'Daylight','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (978,'Deeper Darkness','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (979,'Diminish Plants','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (980,'Dispel Magic','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (981,'Dominate Animal','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (982,'Glyph of Warding','Scroll','Divine','No',NULL,NULL,'575 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (983,'Heal Mount','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (984,'Helping Hand','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (985,'Inflict Serious Wounds','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (986,'Invisibility Purge','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (987,'Locate Object','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (988,'Magic Circle Against Chaos/Evil/Good/Law','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (989,'Magic Fang, Greater','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (990,'Magic Vestment','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (991,'Meld into Stone','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (992,'Neutralize Poison','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (993,'Obscure Object','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (994,'Plant Growth','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (995,'Prayer','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (996,'Protection from Energy','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (997,'Quench','Scroll','Divine','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
