INSERT INTO equipment VALUES (198,'Hourglass','Goods and Services','Item','Tools and Skill Kits','25 gp',NULL,NULL,NULL,NULL,'1 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (199,'Magnifying glass','Goods and Services','Item','Tools and Skill Kits','100 gp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This simple lens allows a closer look at small objects. It is also useful as a substitute for flint and steel when starting fires. Lighting a fire with a magnifying glass requires light as bright as sunlight to focus, tinder to ignite, and at least a full-round action. A magnifying glass grants a +2 circumstance bonus on Appraise checks involving any item that is small or highly detailed.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (200,'Musical instrument, common','Goods and Services','Item','Tools and Skill Kits','5 gp',NULL,NULL,NULL,NULL,'3 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'A masterwork instrument grants a +2 circumstance bonus on Perform checks involving its use.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (201,'Musical instrument, masterwork','Goods and Services','Item','Tools and Skill Kits','100 gp',NULL,NULL,NULL,NULL,'3 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'A masterwork instrument grants a +2 circumstance bonus on Perform checks involving its use.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (202,'Scale, merchant\'s','Goods and Services','Item','Tools and Skill Kits','2 gp',NULL,NULL,NULL,NULL,'1 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'A scale grants a +2 circumstance bonus on Appraise checks involving items that are valued by weight, including anything made of precious metals.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (203,'Spell component pouch','Goods and Services','Item','Tools and Skill Kits','5 gp',NULL,NULL,NULL,NULL,'2 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'A spellcaster with a spell component pouch is assumed to have all the material components and focuses needed for spellcasting, except for those components that have a specific cost, divine focuses, and focuses that wouldn\'t fit in a pouch.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (204,'Spellbook, wizard\'s (blank)','Goods and Services','Item','Tools and Skill Kits','15 gp',NULL,NULL,NULL,NULL,'3 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'A spellbook has 100 pages of parchment, and each spell takes up one page per spell level (one page each for 0-level spells).','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (205,'Thieves\' tools','Goods and Services','Item','Tools and Skill Kits','30 gp',NULL,NULL,NULL,NULL,'1 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This kit contains the tools you need to use the Disable Device and Open Lock skills. Without these tools, you must improvise tools, and you take a -2 circumstance penalty on Disable Device and Open Locks checks.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (206,'Thieves\' tools, masterwork','Goods and Services','Item','Tools and Skill Kits','100 gp',NULL,NULL,NULL,NULL,'2 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This kit contains extra tools and tools of better make, which grant a +2 circumstance bonus on Disable Device and Open Lock checks.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (207,'Tool, masterwork','Goods and Services','Item','Tools and Skill Kits','50 gp',NULL,NULL,NULL,NULL,'1 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This well-made item is the perfect tool for the job. It grants a +2 circumstance bonus on a related skill check (if any). Bonuses provided by multiple masterwork items used toward the same skill check do not stack.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (208,'Water clock','Goods and Services','Item','Tools and Skill Kits','1,000 gp',NULL,NULL,NULL,NULL,'200 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This large, bulky contrivance gives the time accurate to within half an hour per day since it was last set. It requires a source of water, and it must be kept still because it marks time by the regulated flow of droplets of water.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (209,'Artisan\'s outfit','Goods and Services','Item','Clothing','1 gp',NULL,NULL,NULL,NULL,'4 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This outfit includes a shirt with buttons, a skirt or pants with a drawstring, shoes, and perhaps a cap or hat. It may also include a belt or a leather or cloth apron for carrying tools.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (210,'Cleric\'s vestments','Goods and Services','Item','Clothing','5 gp',NULL,NULL,NULL,NULL,'6 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'These ecclesiastical clothes are for performing priestly functions, not for adventuring.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (211,'Cold weather outfit','Goods and Services','Item','Clothing','8 gp',NULL,NULL,NULL,NULL,'7 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'A cold weather outfit includes a wool coat, linen shirt, wool cap, heavy cloak, thick pants or skirt, and boots. This outfit grants a +5 circumstance bonus on Fortitude saving throws against exposure to cold weather.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (212,'Courtier\'s outfit','Goods and Services','Item','Clothing','30 gp',NULL,NULL,NULL,NULL,'6 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This outfit includes fancy, tailored clothes in whatever fashion happens to be the current style in the courts of the nobles. Anyone trying to influence nobles or courtiers while wearing street dress will have a hard time of it (-2 penalty on Charisma-based skill checks to influence such individuals). If you wear this outfit without jewelry (costing an additional 50 gp), you look like an out-of-place commoner.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (213,'Entertainer\'s outfit','Goods and Services','Item','Clothing','3 gp',NULL,NULL,NULL,NULL,'4 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This set of flashy, perhaps even gaudy, clothes is for entertaining. While the outfit looks whimsical, its practical design lets you tumble, dance, walk a tightrope, or just run (if the audience turns ugly).','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (214,'Explorer\'s outfit','Goods and Services','Item','Clothing','10 gp',NULL,NULL,NULL,NULL,'8 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This is a full set of clothes for someone who never knows what to expect. It includes sturdy boots, leather breeches or a skirt, a belt, a shirt (perhaps with a vest or jacket), gloves, and a cloak. Rather than a leather skirt, a leather overtunic may be worn over a cloth skirt. The clothes have plenty of pockets (especially the cloak). The outfit also includes any extra items you might need, such as a scarf or a wide-brimmed hat.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (215,'Monk\'s outfit','Goods and Services','Item','Clothing','5 gp',NULL,NULL,NULL,NULL,'2 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This simple outfit includes sandals, loose breeches, and a loose shirt, and is all bound together with sashes. The outfit is designed to give you maximum mobility, and it\'s made of high-quality fabric. You can hide small weapons in pockets hidden in the folds, and the sashes are strong enough to serve as short ropes.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (216,'Noble\'s outfit','Goods and Services','Item','Clothing','75 gp',NULL,NULL,NULL,NULL,'10 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This set of clothes is designed specifically to be expensive and to show it. Precious metals and gems are worked into the clothing. To fit into the noble crowd, every would-be noble also needs a signet ring (see Adventuring Gear, above) and jewelry (worth at least 100 gp).','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (217,'Peasant\'s outfit','Goods and Services','Item','Clothing','1 sp',NULL,NULL,NULL,NULL,'2 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This set of clothes consists of a loose shirt and baggy breeches, or a loose shirt and skirt or overdress. Cloth wrappings are used for shoes.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (218,'Royal outfit','Goods and Services','Item','Clothing','200 gp',NULL,NULL,NULL,NULL,'15 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This is just the clothing, not the royal scepter, crown, ring, and other accoutrements. Royal clothes are ostentatious, with gems, gold, silk, and fur in abundance.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (219,'Scholar\'s outfit','Goods and Services','Item','Clothing','5 gp',NULL,NULL,NULL,NULL,'6 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Perfect for a scholar, this outfit includes a robe, a belt, a cap, soft shoes, and possibly a cloak.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (220,'Traveler\'s outfit','Goods and Services','Item','Clothing','1 gp',NULL,NULL,NULL,NULL,'5 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This set of clothes consists of boots, a wool skirt or breeches, a sturdy belt, a shirt (perhaps with a vest or jacket), and an ample cloak with a hood.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (221,'Ale, Gallon','Goods and Services','Item','Food, Drink, and Lodging','2 sp',NULL,NULL,NULL,NULL,'8 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (222,'Ale, Mug','Goods and Services','Item','Food, Drink, and Lodging','4 cp',NULL,NULL,NULL,NULL,'1 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (223,'Banquet (per person)','Goods and Services','Item','Food, Drink, and Lodging','10 gp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (224,'Bread, per loaf','Goods and Services','Item','Food, Drink, and Lodging','2 cp',NULL,NULL,NULL,NULL,'1/2 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (225,'Cheese, hunk of','Goods and Services','Item','Food, Drink, and Lodging','1 sp',NULL,NULL,NULL,NULL,'1/2 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (226,'Inn stay (per day), Good','Goods and Services','Item','Food, Drink, and Lodging','2 gp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (227,'Inn stay (per day), Common','Goods and Services','Item','Food, Drink, and Lodging','5 sp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (228,'Inn stay (per day), Poor','Goods and Services','Item','Food, Drink, and Lodging','2 sp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (229,'Meals (per day), Good','Goods and Services','Item','Food, Drink, and Lodging','5 sp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Poor meals might be composed of bread, baked turnips, onions, and water. Common meals might consist of bread, chicken stew, carrots, and watered-down ale or wine. Good meals might be composed of bread and pastries, beef, peas, and ale or wine.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (230,'Meals (per day), Common','Goods and Services','Item','Food, Drink, and Lodging','3 sp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Poor meals might be composed of bread, baked turnips, onions, and water. Common meals might consist of bread, chicken stew, carrots, and watered-down ale or wine. Good meals might be composed of bread and pastries, beef, peas, and ale or wine.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (231,'Meals (per day), Poor','Goods and Services','Item','Food, Drink, and Lodging','1 sp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Poor meals might be composed of bread, baked turnips, onions, and water. Common meals might consist of bread, chicken stew, carrots, and watered-down ale or wine. Good meals might be composed of bread and pastries, beef, peas, and ale or wine.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (232,'Meat, chunk of','Goods and Services','Item','Food, Drink, and Lodging','3 sp',NULL,NULL,NULL,NULL,'1/2 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (233,'Wine, Common (pitcher)','Goods and Services','Item','Food, Drink, and Lodging','2 sp',NULL,NULL,NULL,NULL,'6 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (234,'Wine, Fine (bottle)','Goods and Services','Item','Food, Drink, and Lodging','10 gp',NULL,NULL,NULL,NULL,'1-1/2 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (235,'Barding, Medium creature','Goods and Services','Item','Mounts and Related Gear','x2',NULL,NULL,NULL,NULL,'x1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Barding is a type of armor that covers the head, neck, chest, body, and possibly legs of a horse or other mount. Barding made of medium or heavy armor provides better protection than light barding, but at the expense of speed. Barding can be made of any of the armor types found on Table: Armor and Shields. Armor for a horse (a Large nonhumanoid creature) costs four times as much as armor for a human (a Medium humanoid creature) and also weighs twice as much as the armor found on Table: Armor and Shields (see Armor for Unusual Creatures). If the barding is for a pony or other Medium mount, the cost is only double, and the weight is the same as for Medium armor worn by a humanoid. Medium or heavy barding slows a mount that wears it, as shown on the table below. Flying mounts can\'t fly in medium or heavy barding. Removing and fitting barding takes five times as long as the figures given on Table: Donning Armor. A barded animal cannot be used to carry any load other than the rider and normal saddlebags.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (236,'Barding, Large creature','Goods and Services','Item','Mounts and Related Gear','x4',NULL,NULL,NULL,NULL,'x2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Barding is a type of armor that covers the head, neck, chest, body, and possibly legs of a horse or other mount. Barding made of medium or heavy armor provides better protection than light barding, but at the expense of speed. Barding can be made of any of the armor types found on Table: Armor and Shields. Armor for a horse (a Large nonhumanoid creature) costs four times as much as armor for a human (a Medium humanoid creature) and also weighs twice as much as the armor found on Table: Armor and Shields (see Armor for Unusual Creatures). If the barding is for a pony or other Medium mount, the cost is only double, and the weight is the same as for Medium armor worn by a humanoid. Medium or heavy barding slows a mount that wears it, as shown on the table below. Flying mounts can\'t fly in medium or heavy barding. Removing and fitting barding takes five times as long as the figures given on Table: Donning Armor. A barded animal cannot be used to carry any load other than the rider and normal saddlebags.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (237,'Bit and bridle','Goods and Services','Item','Mounts and Related Gear','2 gp',NULL,NULL,NULL,NULL,'1 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (238,'Dog, guard','Goods and Services','Item','Mounts and Related Gear','25 gp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (239,'Dog, riding','Goods and Services','Item','Mounts and Related Gear','150 gp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This Medium dog is specially trained to carry a Small humanoid rider. It is brave in combat like a warhorse. You take no damage when you fall from a riding dog.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (240,'Donkey or mule','Goods and Services','Item','Mounts and Related Gear','8 gp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Donkeys and mules are stolid in the face of danger, hardy, surefooted, and capable of carrying heavy loads over vast distances. Unlike a horse, a donkey or a mule is willing (though not eager) to enter dungeons and other strange or threatening places.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (241,'Feed (per day)','Goods and Services','Item','Mounts and Related Gear','5 cp',NULL,NULL,NULL,NULL,'10 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Horses, donkeys, mules, and ponies can graze to sustain themselves, but providing feed for them is much better. If you have a riding dog, you have to feed it at least some meat.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (242,'Horse, heavy','Goods and Services','Item','Mounts and Related Gear','200 gp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'A horse (other than a pony) is suitable as a mount for a human, dwarf, elf, half-elf, or half-orc. A pony is smaller than a horse and is a suitable mount for a gnome or halfling. Warhorses and warponies can be ridden easily into combat. Light horses, ponies, and heavy horses are hard to control in combat.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (243,'Horse, light','Goods and Services','Item','Mounts and Related Gear','75 gp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'A horse (other than a pony) is suitable as a mount for a human, dwarf, elf, half-elf, or half-orc. A pony is smaller than a horse and is a suitable mount for a gnome or halfling. Warhorses and warponies can be ridden easily into combat. Light horses, ponies, and heavy horses are hard to control in combat.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (244,'Horse, Pony','Goods and Services','Item','Mounts and Related Gear','30 gp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'A horse (other than a pony) is suitable as a mount for a human, dwarf, elf, half-elf, or half-orc. A pony is smaller than a horse and is a suitable mount for a gnome or halfling. Warhorses and warponies can be ridden easily into combat. Light horses, ponies, and heavy horses are hard to control in combat.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (245,'Horse, Warhorse, heavy','Goods and Services','Item','Mounts and Related Gear','400 gp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'A horse (other than a pony) is suitable as a mount for a human, dwarf, elf, half-elf, or half-orc. A pony is smaller than a horse and is a suitable mount for a gnome or halfling. Warhorses and warponies can be ridden easily into combat. Light horses, ponies, and heavy horses are hard to control in combat.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (246,'Horse, Warhorse, light','Goods and Services','Item','Mounts and Related Gear','150 gp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'A horse (other than a pony) is suitable as a mount for a human, dwarf, elf, half-elf, or half-orc. A pony is smaller than a horse and is a suitable mount for a gnome or halfling. Warhorses and warponies can be ridden easily into combat. Light horses, ponies, and heavy horses are hard to control in combat.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (247,'Horse, Warpony','Goods and Services','Item','Mounts and Related Gear','100 gp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'A horse (other than a pony) is suitable as a mount for a human, dwarf, elf, half-elf, or half-orc. A pony is smaller than a horse and is a suitable mount for a gnome or halfling. Warhorses and warponies can be ridden easily into combat. Light horses, ponies, and heavy horses are hard to control in combat.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (248,'Saddle, Military','Goods and Services','Item','Mounts and Related Gear','20 gp',NULL,NULL,NULL,NULL,'30 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'A military saddle braces the rider, providing a +2 circumstance bonus on Ride checks related to staying in the saddle. If you\'re knocked unconscious while in a military saddle, you have a 75% chance to stay in the saddle (compared to 50% for a riding saddle).','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (249,'Saddle, Pack','Goods and Services','Item','Mounts and Related Gear','5 gp',NULL,NULL,NULL,NULL,'15 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'A pack saddle holds gear and supplies, but not a rider. It holds as much gear as the mount can carry.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (250,'Saddle, Riding','Goods and Services','Item','Mounts and Related Gear','10 gp',NULL,NULL,NULL,NULL,'25 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'The standard riding saddle supports a rider.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (251,'Saddle, Exotic, Military','Goods and Services','Item','Mounts and Related Gear','60 gp',NULL,NULL,NULL,NULL,'40 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'An exotic saddle is like a normal saddle of the same sort except that it is designed for an unusual mount. Exotic saddles come in military, pack, and riding styles. A military saddle braces the rider, providing a +2 circumstance bonus on Ride checks related to staying in the saddle. If you\'re knocked unconscious while in a military saddle, you have a 75% chance to stay in the saddle (compared to 50% for a riding saddle).','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (252,'Saddle, Exotic, Pack','Goods and Services','Item','Mounts and Related Gear','15 gp',NULL,NULL,NULL,NULL,'20 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'An exotic saddle is like a normal saddle of the same sort except that it is designed for an unusual mount. Exotic saddles come in military, pack, and riding styles. A pack saddle holds gear and supplies, but not a rider. It holds as much gear as the mount can carry.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (253,'Saddle, Exotic, Riding','Goods and Services','Item','Mounts and Related Gear','30 gp',NULL,NULL,NULL,NULL,'30 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'An exotic saddle is like a normal saddle of the same sort except that it is designed for an unusual mount. Exotic saddles come in military, pack, and riding styles. The standard riding saddle supports a rider.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (254,'Saddlebags','Goods and Services','Item','Mounts and Related Gear','4 gp',NULL,NULL,NULL,NULL,'8 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (255,'Stabling (per day)','Goods and Services','Item','Mounts and Related Gear','5 sp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (256,'Carriage','Goods and Services','Item','Transport','100 gp',NULL,NULL,NULL,NULL,'600 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This four-wheeled vehicle can transport as many as four people within an enclosed cab, plus two drivers. In general, two horses (or other beasts of burden) draw it. A carriage comes with the harness needed to pull it.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (257,'Cart','Goods and Services','Item','Transport','15 gp',NULL,NULL,NULL,NULL,'200 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This two-wheeled vehicle can be drawn by a single horse (or other beast of burden). It comes with a harness.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (258,'Galley','Goods and Services','Item','Transport','30,000 gp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This three-masted ship has seventy oars on either side and requires a total crew of 200. A galley is 130 feet long and 20 feet wide, and it can carry 150 tons of cargo or 250 soldiers. For 8,000 gp more, it can be fitted with a ram and castles with firing platforms fore, aft, and amidships. This ship cannot make sea voyages and sticks to the coast. It moves about 4 miles per hour when being rowed or under sail.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (259,'Keelboat','Goods and Services','Item','Transport','3,000 gp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This 50- to 75-foot-long ship is 15 to 20 feet wide and has a few oars to supplement its single mast with a square sail. It has a crew of eight to fifteen and can carry 40 to 50 tons of cargo or 100 soldiers. It can make sea voyages, as well as sail down rivers (thanks to its flat bottom). It moves about 1 mile per hour.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (260,'Longship','Goods and Services','Item','Transport','10,000 gp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This 75-foot-long ship with forty oars requires a total crew of 50. It has a single mast and a square sail, and it can carry 50 tons of cargo or 120 soldiers. A longship can make sea voyages. It moves about 3 miles per hour when being rowed or under sail.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (261,'Rowboat','Goods and Services','Item','Transport','50 gp',NULL,NULL,NULL,NULL,'100 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This 8- to 12-foot-long boat holds two or three Medium passengers. It moves about 1-1/2 miles per hour.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (262,'Oar','Goods and Services','Item','Transport','2 gp',NULL,NULL,NULL,NULL,'10 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (263,'Sailing ship','Goods and Services','Item','Transport','10,000 gp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This larger, seaworthy ship is 75 to 90 feet long and 20 feet wide and has a crew of 20. It can carry 150 tons of cargo. It has square sails on its two masts and can make sea voyages. It moves about 2 miles per hour.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (264,'Sled','Goods and Services','Item','Transport','20 gp',NULL,NULL,NULL,NULL,'300 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This is a wagon on runners for moving through snow and over ice. In general, two horses (or other beasts of burden) draw it. A sled comes with the harness needed to pull it.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (265,'Wagon','Goods and Services','Item','Transport','35 gp',NULL,NULL,NULL,NULL,'400 lb.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This is a four-wheeled, open vehicle for transporting heavy loads. In general, two horses (or other beasts of burden) draw it. A wagon comes with the harness needed to pull it.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (266,'Warship','Goods and Services','Item','Transport','25,000 gp',NULL,NULL,NULL,NULL,'-',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This 100-foot-long ship has a single mast, although oars can also propel it. It has a crew of 60 to 80 rowers. This ship can carry 160 soldiers, but not for long distances, since there isn\'t room for supplies to support that many people. The warship cannot make sea voyages and sticks to the coast. It is not used for cargo. It moves about 2-1/2 miles per hour when being rowed or under sail.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (267,'Coach cab','Goods and Services','Service','Spellcasting and Services','3 cp per mile',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'The price given is for a ride in a coach that transports people (and light cargo) between towns. For a ride in a cab that transports passengers within a city, 1 copper piece usually takes you anywhere you need to go.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (268,'Hireling, trained','Goods and Services','Service','Spellcasting and Services','3 sp per day',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'The amount given is the typical daily wage for mercenary warriors, masons, craftsmen, scribes, teamsters, and other trained hirelings. This value represents a minimum wage; many such hirelings require significantly higher pay.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (269,'Hireling, untrained','Goods and Services','Service','Spellcasting and Services','1 sp per day',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'The amount shown is the typical daily wage for laborers, porters, cooks, maids, and other menial workers.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (270,'Messenger','Goods and Services','Service','Spellcasting and Services','2 cp per mile',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'This entry includes horse-riding messengers and runners. Those willing to carry a message to a place they were going anyway may ask for only half the indicated amount.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (271,'Road or gate toll','Goods and Services','Service','Spellcasting and Services','1 cp',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'A toll is sometimes charged to cross a well-trodden, well-kept, and well-guarded road to pay for patrols on it and for its upkeep. Occasionally, a large walled city charges a toll to enter or exit (or sometimes just to enter).','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (272,'Ship\'s passage','Goods and Services','Service','Spellcasting and Services','1 sp per mile',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Most ships do not specialize in passengers, but many have the capability to take a few along when transporting cargo. Double the given cost for creatures larger than Medium or creatures that are otherwise difficult to bring aboard a ship.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (273,'Spell, 0-level','Goods and Services','Service','Spellcasting and Services','Caster level x5 gp',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'The indicated amount is how much it costs to get a spellcaster to cast a spell for you. This cost assumes that you can go to the spellcaster and have the spell cast at his or her convenience (generally at least 24 hours later, so that the spellcaster has time to prepare the spell in question). If you want to bring the spellcaster somewhere to cast a spell you need to negotiate with him or her, and the default answer is no. The cost given is for a spell with no cost for a material component or focus component and no XP cost. If the spell includes a material component, add the cost of that component to the cost of the spell. If the spell has a focus component (other than a divine focus), add 1/10 the cost of that focus to the cost of the spell. If the spell has an XP cost, add 5 gp per XP lost. Furthermore, if a spell has dangerous consequences, the spellcaster will certainly require proof that you can and will pay for dealing with any such consequences (that is, assuming that the spellcaster even agrees to cast such a spell, which isn\'t certain). In the case of spells that transport the caster and characters over a distance, you will likely have to pay for two castings of the spell, even if you aren\'t returning with the caster. In addition, not every town or village has a spellcaster of sufficient level to cast any spell. In general, you must travel to a small town (or larger settlement) to be reasonably assured of finding a spellcaster capable of casting 1st-level spells, a large town for 2nd-level spells, a small city for 3rd- or 4th-level spells, a large city for 5th- or 6th-level spells, and a metropolis for 7th- or 8th-level spells. Even a metropolis isn\'t guaranteed to have a local spellcaster able to cast 9th-level spells.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (274,'Spell, 1st-level','Goods and Services','Service','Spellcasting and Services','Caster level x10 gp',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'The indicated amount is how much it costs to get a spellcaster to cast a spell for you. This cost assumes that you can go to the spellcaster and have the spell cast at his or her convenience (generally at least 24 hours later, so that the spellcaster has time to prepare the spell in question). If you want to bring the spellcaster somewhere to cast a spell you need to negotiate with him or her, and the default answer is no. The cost given is for a spell with no cost for a material component or focus component and no XP cost. If the spell includes a material component, add the cost of that component to the cost of the spell. If the spell has a focus component (other than a divine focus), add 1/10 the cost of that focus to the cost of the spell. If the spell has an XP cost, add 5 gp per XP lost. Furthermore, if a spell has dangerous consequences, the spellcaster will certainly require proof that you can and will pay for dealing with any such consequences (that is, assuming that the spellcaster even agrees to cast such a spell, which isn\'t certain). In the case of spells that transport the caster and characters over a distance, you will likely have to pay for two castings of the spell, even if you aren\'t returning with the caster. In addition, not every town or village has a spellcaster of sufficient level to cast any spell. In general, you must travel to a small town (or larger settlement) to be reasonably assured of finding a spellcaster capable of casting 1st-level spells, a large town for 2nd-level spells, a small city for 3rd- or 4th-level spells, a large city for 5th- or 6th-level spells, and a metropolis for 7th- or 8th-level spells. Even a metropolis isn\'t guaranteed to have a local spellcaster able to cast 9th-level spells.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (275,'Spell, 2nd-level','Goods and Services','Service','Spellcasting and Services','Caster level x20 gp',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'The indicated amount is how much it costs to get a spellcaster to cast a spell for you. This cost assumes that you can go to the spellcaster and have the spell cast at his or her convenience (generally at least 24 hours later, so that the spellcaster has time to prepare the spell in question). If you want to bring the spellcaster somewhere to cast a spell you need to negotiate with him or her, and the default answer is no. The cost given is for a spell with no cost for a material component or focus component and no XP cost. If the spell includes a material component, add the cost of that component to the cost of the spell. If the spell has a focus component (other than a divine focus), add 1/10 the cost of that focus to the cost of the spell. If the spell has an XP cost, add 5 gp per XP lost. Furthermore, if a spell has dangerous consequences, the spellcaster will certainly require proof that you can and will pay for dealing with any such consequences (that is, assuming that the spellcaster even agrees to cast such a spell, which isn\'t certain). In the case of spells that transport the caster and characters over a distance, you will likely have to pay for two castings of the spell, even if you aren\'t returning with the caster. In addition, not every town or village has a spellcaster of sufficient level to cast any spell. In general, you must travel to a small town (or larger settlement) to be reasonably assured of finding a spellcaster capable of casting 1st-level spells, a large town for 2nd-level spells, a small city for 3rd- or 4th-level spells, a large city for 5th- or 6th-level spells, and a metropolis for 7th- or 8th-level spells. Even a metropolis isn\'t guaranteed to have a local spellcaster able to cast 9th-level spells.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (276,'Spell, 3rd-level','Goods and Services','Service','Spellcasting and Services','Caster level x30 gp',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'The indicated amount is how much it costs to get a spellcaster to cast a spell for you. This cost assumes that you can go to the spellcaster and have the spell cast at his or her convenience (generally at least 24 hours later, so that the spellcaster has time to prepare the spell in question). If you want to bring the spellcaster somewhere to cast a spell you need to negotiate with him or her, and the default answer is no. The cost given is for a spell with no cost for a material component or focus component and no XP cost. If the spell includes a material component, add the cost of that component to the cost of the spell. If the spell has a focus component (other than a divine focus), add 1/10 the cost of that focus to the cost of the spell. If the spell has an XP cost, add 5 gp per XP lost. Furthermore, if a spell has dangerous consequences, the spellcaster will certainly require proof that you can and will pay for dealing with any such consequences (that is, assuming that the spellcaster even agrees to cast such a spell, which isn\'t certain). In the case of spells that transport the caster and characters over a distance, you will likely have to pay for two castings of the spell, even if you aren\'t returning with the caster. In addition, not every town or village has a spellcaster of sufficient level to cast any spell. In general, you must travel to a small town (or larger settlement) to be reasonably assured of finding a spellcaster capable of casting 1st-level spells, a large town for 2nd-level spells, a small city for 3rd- or 4th-level spells, a large city for 5th- or 6th-level spells, and a metropolis for 7th- or 8th-level spells. Even a metropolis isn\'t guaranteed to have a local spellcaster able to cast 9th-level spells.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (277,'Spell, 4th-level','Goods and Services','Service','Spellcasting and Services','Caster level x40 gp',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'The indicated amount is how much it costs to get a spellcaster to cast a spell for you. This cost assumes that you can go to the spellcaster and have the spell cast at his or her convenience (generally at least 24 hours later, so that the spellcaster has time to prepare the spell in question). If you want to bring the spellcaster somewhere to cast a spell you need to negotiate with him or her, and the default answer is no. The cost given is for a spell with no cost for a material component or focus component and no XP cost. If the spell includes a material component, add the cost of that component to the cost of the spell. If the spell has a focus component (other than a divine focus), add 1/10 the cost of that focus to the cost of the spell. If the spell has an XP cost, add 5 gp per XP lost. Furthermore, if a spell has dangerous consequences, the spellcaster will certainly require proof that you can and will pay for dealing with any such consequences (that is, assuming that the spellcaster even agrees to cast such a spell, which isn\'t certain). In the case of spells that transport the caster and characters over a distance, you will likely have to pay for two castings of the spell, even if you aren\'t returning with the caster. In addition, not every town or village has a spellcaster of sufficient level to cast any spell. In general, you must travel to a small town (or larger settlement) to be reasonably assured of finding a spellcaster capable of casting 1st-level spells, a large town for 2nd-level spells, a small city for 3rd- or 4th-level spells, a large city for 5th- or 6th-level spells, and a metropolis for 7th- or 8th-level spells. Even a metropolis isn\'t guaranteed to have a local spellcaster able to cast 9th-level spells.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (278,'Spell, 5th-level','Goods and Services','Service','Spellcasting and Services','Caster level x50 gp',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'The indicated amount is how much it costs to get a spellcaster to cast a spell for you. This cost assumes that you can go to the spellcaster and have the spell cast at his or her convenience (generally at least 24 hours later, so that the spellcaster has time to prepare the spell in question). If you want to bring the spellcaster somewhere to cast a spell you need to negotiate with him or her, and the default answer is no. The cost given is for a spell with no cost for a material component or focus component and no XP cost. If the spell includes a material component, add the cost of that component to the cost of the spell. If the spell has a focus component (other than a divine focus), add 1/10 the cost of that focus to the cost of the spell. If the spell has an XP cost, add 5 gp per XP lost. Furthermore, if a spell has dangerous consequences, the spellcaster will certainly require proof that you can and will pay for dealing with any such consequences (that is, assuming that the spellcaster even agrees to cast such a spell, which isn\'t certain). In the case of spells that transport the caster and characters over a distance, you will likely have to pay for two castings of the spell, even if you aren\'t returning with the caster. In addition, not every town or village has a spellcaster of sufficient level to cast any spell. In general, you must travel to a small town (or larger settlement) to be reasonably assured of finding a spellcaster capable of casting 1st-level spells, a large town for 2nd-level spells, a small city for 3rd- or 4th-level spells, a large city for 5th- or 6th-level spells, and a metropolis for 7th- or 8th-level spells. Even a metropolis isn\'t guaranteed to have a local spellcaster able to cast 9th-level spells.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (279,'Spell, 6th-level','Goods and Services','Service','Spellcasting and Services','Caster level x60 gp',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'The indicated amount is how much it costs to get a spellcaster to cast a spell for you. This cost assumes that you can go to the spellcaster and have the spell cast at his or her convenience (generally at least 24 hours later, so that the spellcaster has time to prepare the spell in question). If you want to bring the spellcaster somewhere to cast a spell you need to negotiate with him or her, and the default answer is no. The cost given is for a spell with no cost for a material component or focus component and no XP cost. If the spell includes a material component, add the cost of that component to the cost of the spell. If the spell has a focus component (other than a divine focus), add 1/10 the cost of that focus to the cost of the spell. If the spell has an XP cost, add 5 gp per XP lost. Furthermore, if a spell has dangerous consequences, the spellcaster will certainly require proof that you can and will pay for dealing with any such consequences (that is, assuming that the spellcaster even agrees to cast such a spell, which isn\'t certain). In the case of spells that transport the caster and characters over a distance, you will likely have to pay for two castings of the spell, even if you aren\'t returning with the caster. In addition, not every town or village has a spellcaster of sufficient level to cast any spell. In general, you must travel to a small town (or larger settlement) to be reasonably assured of finding a spellcaster capable of casting 1st-level spells, a large town for 2nd-level spells, a small city for 3rd- or 4th-level spells, a large city for 5th- or 6th-level spells, and a metropolis for 7th- or 8th-level spells. Even a metropolis isn\'t guaranteed to have a local spellcaster able to cast 9th-level spells.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (280,'Spell, 7th-level','Goods and Services','Service','Spellcasting and Services','Caster level x70 gp',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'The indicated amount is how much it costs to get a spellcaster to cast a spell for you. This cost assumes that you can go to the spellcaster and have the spell cast at his or her convenience (generally at least 24 hours later, so that the spellcaster has time to prepare the spell in question). If you want to bring the spellcaster somewhere to cast a spell you need to negotiate with him or her, and the default answer is no. The cost given is for a spell with no cost for a material component or focus component and no XP cost. If the spell includes a material component, add the cost of that component to the cost of the spell. If the spell has a focus component (other than a divine focus), add 1/10 the cost of that focus to the cost of the spell. If the spell has an XP cost, add 5 gp per XP lost. Furthermore, if a spell has dangerous consequences, the spellcaster will certainly require proof that you can and will pay for dealing with any such consequences (that is, assuming that the spellcaster even agrees to cast such a spell, which isn\'t certain). In the case of spells that transport the caster and characters over a distance, you will likely have to pay for two castings of the spell, even if you aren\'t returning with the caster. In addition, not every town or village has a spellcaster of sufficient level to cast any spell. In general, you must travel to a small town (or larger settlement) to be reasonably assured of finding a spellcaster capable of casting 1st-level spells, a large town for 2nd-level spells, a small city for 3rd- or 4th-level spells, a large city for 5th- or 6th-level spells, and a metropolis for 7th- or 8th-level spells. Even a metropolis isn\'t guaranteed to have a local spellcaster able to cast 9th-level spells.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (281,'Spell, 8th-level','Goods and Services','Service','Spellcasting and Services','Caster level x80 gp',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'The indicated amount is how much it costs to get a spellcaster to cast a spell for you. This cost assumes that you can go to the spellcaster and have the spell cast at his or her convenience (generally at least 24 hours later, so that the spellcaster has time to prepare the spell in question). If you want to bring the spellcaster somewhere to cast a spell you need to negotiate with him or her, and the default answer is no. The cost given is for a spell with no cost for a material component or focus component and no XP cost. If the spell includes a material component, add the cost of that component to the cost of the spell. If the spell has a focus component (other than a divine focus), add 1/10 the cost of that focus to the cost of the spell. If the spell has an XP cost, add 5 gp per XP lost. Furthermore, if a spell has dangerous consequences, the spellcaster will certainly require proof that you can and will pay for dealing with any such consequences (that is, assuming that the spellcaster even agrees to cast such a spell, which isn\'t certain). In the case of spells that transport the caster and characters over a distance, you will likely have to pay for two castings of the spell, even if you aren\'t returning with the caster. In addition, not every town or village has a spellcaster of sufficient level to cast any spell. In general, you must travel to a small town (or larger settlement) to be reasonably assured of finding a spellcaster capable of casting 1st-level spells, a large town for 2nd-level spells, a small city for 3rd- or 4th-level spells, a large city for 5th- or 6th-level spells, and a metropolis for 7th- or 8th-level spells. Even a metropolis isn\'t guaranteed to have a local spellcaster able to cast 9th-level spells.','SRD 3.5 Equipment');
INSERT INTO equipment VALUES (282,'Spell, 9th-level','Goods and Services','Service','Spellcasting and Services','Caster level x90 gp',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'The indicated amount is how much it costs to get a spellcaster to cast a spell for you. This cost assumes that you can go to the spellcaster and have the spell cast at his or her convenience (generally at least 24 hours later, so that the spellcaster has time to prepare the spell in question). If you want to bring the spellcaster somewhere to cast a spell you need to negotiate with him or her, and the default answer is no. The cost given is for a spell with no cost for a material component or focus component and no XP cost. If the spell includes a material component, add the cost of that component to the cost of the spell. If the spell has a focus component (other than a divine focus), add 1/10 the cost of that focus to the cost of the spell. If the spell has an XP cost, add 5 gp per XP lost. Furthermore, if a spell has dangerous consequences, the spellcaster will certainly require proof that you can and will pay for dealing with any such consequences (that is, assuming that the spellcaster even agrees to cast such a spell, which isn\'t certain). In the case of spells that transport the caster and characters over a distance, you will likely have to pay for two castings of the spell, even if you aren\'t returning with the caster. In addition, not every town or village has a spellcaster of sufficient level to cast any spell. In general, you must travel to a small town (or larger settlement) to be reasonably assured of finding a spellcaster capable of casting 1st-level spells, a large town for 2nd-level spells, a small city for 3rd- or 4th-level spells, a large city for 5th- or 6th-level spells, and a metropolis for 7th- or 8th-level spells. Even a metropolis isn\'t guaranteed to have a local spellcaster able to cast 9th-level spells.','SRD 3.5 Equipment');

--
-- Table structure for table `feat`
--

CREATE TABLE feat (
  id int(10) unsigned NOT NULL auto_increment,
  name varchar(100) NOT NULL default '',
  type varchar(255) default '',
  multiple varchar(255) default '',
  stack varchar(255) default '',
  choice varchar(255) default '',
  prerequisite longtext,
  benefit longtext,
  normal longtext,
  special longtext,
  full_text longtext,
  reference varchar(255) default '',
  PRIMARY KEY  (id),
  KEY id (id),
  KEY name (name)
) TYPE=MyISAM;
