INSERT INTO item VALUES (598,'Keen Edge','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (599,'Tiny Hut','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (600,'Lightning Bolt','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (601,'Magic Circle Against Chaos/Evil/Good/Law','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (602,'Magic Weapon, Greater','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (603,'Major Image','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (604,'Nondetection','Scroll','Arcane','No',NULL,NULL,'425 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (605,'Phantom Steed','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (606,'Protection from Energy','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (607,'Rage','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (608,'Ray of Exhaustion','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (609,'Sculpt Sound','Scroll','Arcane','No',NULL,NULL,'525 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (610,'Secret Page','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (611,'Sepia Snake Sigil','Scroll','Arcane','No',NULL,NULL,'875 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (612,'Shrink Item','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (613,'Sleet Storm','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (614,'Slow','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (615,'Speak with Animals','Scroll','Arcane','No',NULL,NULL,'525 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (616,'Stinking Cloud','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (617,'Suggestion','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (618,'Summon Monster III','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (619,'Tongues','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (620,'Vampiric Touch','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (621,'Water Breathing','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (622,'Wind Wall','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (623,'Animate Dead','Scroll','Arcane','No',NULL,NULL,'1,050 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (624,'Arcane Eye','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (625,'Bestow Curse','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (626,'Charm Monster','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (627,'Confusion','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (628,'Contagion','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (629,'Crushing Despair','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (630,'Cure Critical Wounds','Scroll','Arcane','No',NULL,NULL,'1,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (631,'Detect Scrying','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (632,'Dimension Door','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (633,'Dimensional Anchor','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (634,'Enervation','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (635,'Enlarge Person, Mass','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (636,'Black Tentacles','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (637,'Fear','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (638,'Fire Shield','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (639,'Fire Trap','Scroll','Arcane','No',NULL,NULL,'725 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (640,'Freedom of Movement','Scroll','Arcane','No',NULL,NULL,'1,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (641,'Geas, Lesser','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (642,'Globe of Invulnerability, Lesser','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (643,'Hallucinatory Terrain','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (644,'Ice Storm','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (645,'Illusory Wall','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (646,'Invisibility, Greater','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (647,'Secure Shelter','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (648,'Locate Creature','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (649,'Minor Creation','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (650,'Modify Memory','Scroll','Arcane','No',NULL,NULL,'1,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (651,'Neutralize Poison','Scroll','Arcane','No',NULL,NULL,'1,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (652,'Resilient Sphere','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (653,'Phantasmal Killer','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (654,'Polymorph','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (655,'Rainbow Pattern','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (656,'Mnemonic Enhancer','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (657,'Reduce Person, Mass','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (658,'Remove Curse','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (659,'Repel Vermin','Scroll','Arcane','No',NULL,NULL,'1,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (660,'Scrying','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (661,'Shadow Conjuration','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (662,'Shout','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (663,'Solid Fog','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (664,'Speak with Plants','Scroll','Arcane','No',NULL,NULL,'1,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (665,'Stone Shape','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (666,'Stoneskin','Scroll','Arcane','No',NULL,NULL,'950 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (667,'Summon Monster IV','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (668,'Wall of Fire','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (669,'Wall of Ice','Scroll','Arcane','No',NULL,NULL,'700 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (670,'Zone of Silence','Scroll','Arcane','No',NULL,NULL,'1,000 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (671,'Animal Growth','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (672,'Baleful Polymorph','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (673,'Interposing Hand','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (674,'Blight','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (675,'Break Enchantment','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (676,'Cloudkill','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (677,'Cone of Cold','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (678,'Contact Other Plane','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (679,'Cure Light Wounds, Mass','Scroll','Arcane','No',NULL,NULL,'1,625 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (680,'Dismissal','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (681,'Dispel Magic, Greater','Scroll','Arcane','No',NULL,NULL,'1,625 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (682,'Dominate Person','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (683,'Dream','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (684,'Fabricate','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (685,'False Vision','Scroll','Arcane','No',NULL,NULL,'1,375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (686,'Feeblemind','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (687,'Hold Monster','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (688,'Secret Chest','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (689,'Magic Jar','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (690,'Major Creation','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (691,'Mind Fog','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (692,'Mirage Arcana','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (693,'Mage\'s Faithful Hound','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (694,'Mage\'s Private Sanctum','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (695,'Nightmare','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (696,'Overland Flight','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (697,'Passwall','Scroll','Arcane','No',NULL,NULL,'1,125 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
