INSERT INTO item VALUES (498,'Mage Armor','Scroll','Arcane','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (499,'Magic Missile','Scroll','Arcane','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (500,'Magic Weapon','Scroll','Arcane','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (501,'Mount','Scroll','Arcane','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (502,'Magic Aura','Scroll','Arcane','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (503,'Obscuring Mist','Scroll','Arcane','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (504,'Protection from Chaos/Evil/Good/Law','Scroll','Arcane','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (505,'Ray of Enfeeblement','Scroll','Arcane','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (506,'Reduce Person','Scroll','Arcane','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (507,'Remove Fear','Scroll','Arcane','No',NULL,NULL,'50 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (508,'Shield','Scroll','Arcane','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (509,'Shocking Grasp','Scroll','Arcane','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (510,'Silent Image','Scroll','Arcane','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (511,'Sleep','Scroll','Arcane','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (512,'Summon Monster I','Scroll','Arcane','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (513,'Floating Disk','Scroll','Arcane','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (514,'True Strike','Scroll','Arcane','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (515,'Undetectable Alignment','Scroll','Arcane','No',NULL,NULL,'50 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (516,'Unseen Servant','Scroll','Arcane','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (517,'Ventriloquism','Scroll','Arcane','No',NULL,NULL,'25 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (518,'Animal Messenger','Scroll','Arcane','No',NULL,NULL,'200 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (519,'Animal Trance','Scroll','Arcane','No',NULL,NULL,'200 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (520,'Arcane Lock','Scroll','Arcane','No',NULL,NULL,'175 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (521,'Bear\'s Endurance','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (522,'Blindness/Deafness','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (523,'Blur','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (524,'Bull\'s Strength','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (525,'Calm Emotions','Scroll','Arcane','No',NULL,NULL,'200 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (526,'Cat\'s Grace','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (527,'Command Undead','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (528,'Continual Flame','Scroll','Arcane','No',NULL,NULL,'200 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (529,'Cure Moderate Wounds','Scroll','Arcane','No',NULL,NULL,'200 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (530,'Darkness','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (531,'Darkvision','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (532,'Daze Monster','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (533,'Delay Poison','Scroll','Arcane','No',NULL,NULL,'200 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (534,'Detect Thoughts','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (535,'Disguise Self','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (536,'Eagle\'s Splendor','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (537,'Enthrall','Scroll','Arcane','No',NULL,NULL,'200 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (538,'False Life','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (539,'Flaming Sphere','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (540,'Fog Cloud','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (541,'Fox\'s Cunning','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (542,'Ghoul Touch','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (543,'Glitterdust','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (544,'Gust of Wind','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (545,'Hypnotic Pattern','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (546,'Invisibility','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (547,'Knock','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (548,'Phantom Trap','Scroll','Arcane','No',NULL,NULL,'200 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (549,'Levitate','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (550,'Locate Object','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (551,'Magic Mouth','Scroll','Arcane','No',NULL,NULL,'160 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (552,'Acid Arrow','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (553,'Minor Image','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (554,'Mirror Image','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (555,'Misdirection','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (556,'Obscure Object','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (557,'Owl\'s Wisdom','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (558,'Protection from Arrows','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (559,'Pyrotechnics','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (560,'Resist Energy','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (561,'Rope Trick','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (562,'Scare','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (563,'Scorching Ray','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (564,'See Invisibility','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (565,'Shatter','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (566,'Silence','Scroll','Arcane','No',NULL,NULL,'200 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (567,'Sound Burst','Scroll','Arcane','No',NULL,NULL,'200 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (568,'Spectral Hand','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (569,'Spider Climb','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (570,'Summon Monster II','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (571,'Summon Swarm','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (572,'Hideous Laughter','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (573,'Touch of Idiocy','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (574,'Web','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (575,'Whispering Wind','Scroll','Arcane','No',NULL,NULL,'150 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (576,'Arcane Sight','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (577,'Blink','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (578,'Clairaudience/Clairvoyance','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (579,'Cure Serious Wounds','Scroll','Arcane','No',NULL,NULL,'525 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (580,'Daylight','Scroll','Arcane','No',NULL,NULL,'525 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (581,'Deep Slumber','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (582,'Dispel Magic','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (583,'Displacement','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (584,'Explosive Runes','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (585,'Fireball','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (586,'Flame Arrow','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (587,'Fly','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (588,'Gaseous Form','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (589,'Gentle Repose','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (590,'Glibness','Scroll','Arcane','No',NULL,NULL,'525 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (591,'Good Hope','Scroll','Arcane','No',NULL,NULL,'525 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (592,'Halt Undead','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (593,'Haste','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (594,'Heroism','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (595,'Hold Person','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (596,'Illusory Script','Scroll','Arcane','No',NULL,NULL,'425 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
INSERT INTO item VALUES (597,'Invisibility Sphere','Scroll','Arcane','No',NULL,NULL,'375 gp',NULL,NULL,NULL,NULL,NULL,'SRD 3.5 MagicItemsIV');
